#!/bin/bash

filter="$(cat /root/filter)"

while :
do

if amixer cget numid=4 |grep -v "values=1," |grep values=1 >/dev/nul 2>&1 && amixer cget numid=5 |grep values=0 >/dev/nul 2>&1 && [ "$filter" != "(Slow Rolloff)" ]
then
   echo "(Slow Rolloff)" > /root/filter
   systemctl restart volume
fi

if amixer cget numid=4 |grep values=0 >/dev/nul 2>&1 && amixer cget numid=5 |grep values=0 >/dev/nul 2>&1 && [ "$filter" != "(Fast Rolloff)" ]
then
   echo "(Fast Rolloff)" > /root/filter
   systemctl restart volume
fi

if amixer cget numid=4 |grep values=2 >/dev/nul 2>&1 && amixer cget numid=5 |grep values=0 >/dev/nul 2>&1 && [ "$filter" != "(Minimal Phase)" ]
then
   echo "(Minimal Phase)" > /root/filter
   systemctl restart volume
fi

if amixer cget numid=5 |grep -v "values=1," |grep values=1 >/dev/nul 2>&1 && [ "$filter" != "(N.O.S)" ]
then
   echo "(N.O.S)" > /root/filter
   systemctl restart volume
fi

if [ "mpc volume | tr -dc '0-9'" != "cat /root/vol" ]; then
   sleep 0.2
   mpc volume | tr -dc '0-9' >/root/vol
fi

done
